name: Stock Alarm Bot

on:
  schedule:
    # UTC 기준 (한국시간 - 9시간)
    # 09:02 ~ 15:42까지 20분마다 실행 (평일 월-금)
    - cron: '2,22,42 0-6 * * 1-5'
  workflow_dispatch: # 수동 실행 버튼 활성화

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install requests beautifulsoup4

      - name: Run script
        run: python stock_bot.py
