name: Stock Alarm Bot

on:
  schedule:
    # 한국 시간 기준: 오전 6시 9분 ~ 오후 3시 49분까지 작동
    # (UTC 기준: 전날 21시 ~ 당일 06시)
    - cron: '9,29,49 21-23,0-6 * * 1-5'
  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install requests beautifulsoup4

      - name: Run script
        run: python stock_bot.py
